[app]
description = "A CLI template for bootstrapping Bun applications"
name = "helloc"
version = "0.2.4"

[[commands]]
description = "Hello world command"
name = "hello"
subcommands = false

[[commands]]
description = "Install tools"
name = "install"
subcommands = true

[[commands.children]]
description = "Download and install Task"
name = "task"
subcommands = false
